Add DirectConnection Option in MongoDB SDK (#15968)
We currently have a ReplicaSetNoPrimary error caused by
MongoServerSelectionError: connection timed out\n
{"reason"=>{"type"=>"ReplicaSetNoPrimary", "servers"=>{},
"stale"=>"REDACTED", "compatible"=>"REDACTED",
"heartbeatFrequencyMS"=>"REDACTED", "localThresholdMS"=>"REDACTED",
"setName"=>"REDACTED", "maxElectionId"=>nil,
"maxSetVersion"=>"REDACTED", "commonWireVersion"=>"REDACTED",
"logicalSessionTimeoutMinutes"=>nil},
"name"=>"MongoServerSelectionError", "message"=>"connection timed out",
"stack"=>"MongoServerSelectionError: connection timed out\n at
Timeout._onTimeout (/usr/src/server/bundle/alfred/www.js:126365:34)\n at
listOnTimeout (node:internal/timers:559:17)\n at processTimers
(node:internal/timers:502:7)"}

From:
https://stackoverflow.com/questions/59162342/mongodb-connection-error-mongotimeouterror-server-selection-timed-out-after-30,
we can fix it by enabling directConnection flag as true.

Here is the definition for directConnection:
https://mongodb.github.io/node-mongodb-native/4.14/interfaces/MongoClientOptions.html#directConnection